spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:2727/realms/acme-corporation
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
